# Packages needed for stage 06 (run once inside the project so renv records them)
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
for (p in c("harmony", "patchwork", "dplyr", "tidyr", "ggplot2"))
  if (!requireNamespace(p, quietly = TRUE)) install.packages(p)
for (p in c("scDblFinder", "SingleCellExperiment", "BiocParallel"))
  if (!requireNamespace(p, quietly = TRUE)) BiocManager::install(p, update = FALSE, ask = FALSE)
if (!requireNamespace("presto", quietly = TRUE))   # makes FindAllMarkers much faster (optional)
  try(remotes::install_github("immunogenomics/presto"), silent = TRUE)
if (requireNamespace("renv", quietly = TRUE)) renv::snapshot(prompt = FALSE)
message("Stage 06 packages ready.")
